language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 5.5
      env: DEPENDENCIES='low'
    - php: 5.5
    - php: 5.6
    - php: 5.6
      env: DEPENDENCIES='dev'
    - php: hhvm
    - php: 7.0
  allow_failures:
    - env: DEPENDENCIES='dev'
    - php: hhvm
  fast_finish: true

before_install:
  - composer selfupdate
  - if [ "$DEPENDENCIES" == "low" ]; then composer config disable-tls true; fi;
  - if [ "$DEPENDENCIES" == "low" ]; then composer config secure-http false; fi;

install:
  - phpenv rehash
  - if [ "$DEPENDENCIES" == "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
  - if [ "$DEPENDENCIES" != "low" ]; then composer update; fi;
  - if [ "$DEPENDENCIES" == "low" ]; then composer update --prefer-lowest; fi;

script:
  - './vendor/bin/phpunit --testdox'

notifications:
  email: false