language: php

php:
  - 5.5
  - 5.6
  - hhvm
  - 7.0

matrix:
  allow_failures:
    - php: hhvm

install:
  - composer self-update
  - composer install --dev

before_script:
  - phpenv rehash

script:
  - './vendor/bin/phpunit'

notifications:
  email: false