language: php

php:
  - 5.5
  - 5.6
  - hhvm
  - 7.0

matrix:
  allow_failures:
    - php: hhvm
  include:
    - php: 5.3.3
      env: dependencies=lowest

install:
  - composer self-update

before_script:
  - phpenv rehash
  - if [ "$dependencies" = "lowest" ]; then composer config -- disable-tls true; composer update --prefer-lowest --prefer-stable; else composer install; fi;

script:
  - './vendor/bin/phpunit'

notifications:
  email: false